List<Map<String, dynamic>> degrees = [
{
'id': 1,
'college': 'College of Engineering',
'collegeAbbreviation': 'CoE',
'code': 'BS_CE',
'name': 'BS Civil Engineering',
},
{
'id': 2,
'college': 'College of Engineering',
'collegeAbbreviation': 'CoE',
'code': 'BS_ChE',
'name': 'BS Chemical Engineering',
},
{
'id': 3,
'college': 'College of Engineering',
'collegeAbbreviation': 'CoE',
'code': 'BS_CS',
'name': 'BS Computer Science',
},
{
'id': 4,
'college': 'College of Engineering',
'collegeAbbreviation': 'CoE',
'code': 'BS_CoE',
'name': 'BS in Computer Engineering',
},
{
'id': 5,
'college': 'College of Engineering',
'collegeAbbreviation': 'CoE',
'code': 'BS_EE',
'name': 'BS in Electrical Engineering',
},
{
'id': 6,
'college': 'College of Engineering',
'collegeAbbreviation': 'CoE',
'code': 'BS_EcE',
'name': 'BS in Electronics and Communications Engineering',
},
{
'id': 7,
'college': 'College of Engineering',
'collegeAbbreviation': 'CoE',
'code': 'BS_GE',
'name': 'BS in Geodetic Engineering',
},
{
'id': 8,
'college': 'College of Engineering',
'collegeAbbreviation': 'CoE',
'code': 'BS_IE',
'name': 'BS Industrial Engineering',
},
{
'id': 9,
'college': 'College of Engineering',
'collegeAbbreviation': 'CoE',
'code': 'BS_ME',
'name': 'BS Mechanical Engineering',
},
{
'id': 10,
'college': 'College of Engineering',
'collegeAbbreviation': 'CoE',
'code': 'BS_MatE',
'name': 'BS Materials Engineering',
},
{
'id': 11,
'college': 'College of Engineering',
'collegeAbbreviation': 'CoE',
'code': 'BS_MetE',
'name': 'BS Metallurgical Engineering',
},
  {
    'id': 12,
    'college': 'College of Engineering',
    'collegeAbbreviation': 'CoE',
    'code': 'BS_EM',
    'name': 'BS Mining Engineering',
  },
  {
    'id': 13,
    'college': 'College of Social Sciences and Philosophy',
    'collegeAbbreviation': 'CSSP',
    'code': 'BA_Anthro',
    'name': 'BA Anthropology',
  },
  {
    'id': 14,
    'college': 'College of Social Sciences and Philosophy',
    'collegeAbbreviation': 'CSSP',
    'code': 'BS_Geog',
    'name': 'BS Geography',
  },
  {
    'id': 15,
    'college': 'College of Social Sciences and Philosophy',
    'collegeAbbreviation': 'CSSP',
    'code': 'BA_Hist',
    'name': 'BA History',
  },
  {
    'id': 16,
    'college': 'College of Social Sciences and Philosophy',
    'collegeAbbreviation': 'CSSP',
    'code': 'BA_Ling',
    'name': 'BA Linguistics',
  },
  {
    'id': 17,
    'college': 'College of Social Sciences and Philosophy',
    'collegeAbbreviation': 'CSSP',
    'code': 'BA_Philo',
    'name': 'BA Philosophy',
  },
  {
    'id': 18,
    'college': 'College of Social Sciences and Philosophy',
    'collegeAbbreviation': 'CSSP',
    'code': 'BA_Pol_Sci',
    'name': 'BA Political Science',
  }
  ,{
    'id': 19,
    'college': 'College of Social Sciences and Philosophy',
    'collegeAbbreviation': 'CSSP',
    'code': 'BA_Psych',
    'name': 'BA Psychology',
  },
  {
    'id': 20,
    'college': 'College of Social Sciences and Philosophy',
    'collegeAbbreviation': 'CSSP',
    'code': 'BS_Psych',
    'name': 'BS Psychology',
  },
  {
    'id': 21,
    'college': 'College of Social Sciences and Philosophy',
    'collegeAbbreviation': 'CSSP',
    'code': 'BA_Socio',
    'name': 'BA Sociology',
  },
  ];